### ISSUE TITLE
Remove API Node dependency

### ISSUE THREAD

**Issue by Devel484** [SwitcheoCommunityFund/ethereum-switcheo-tradehub-airdrop#1]
Define constant variable to define a API Node.

Currently hardcoded: https://tradescan.switcheo.org

Example: http://168.119.70.59:5001/get_account?account=swth1p4g4va34a4ea55x0cc4wlsuuwaeppnfv8ane4r
Node: Degen Power Sentry 1

Every Sentry Node is a potential API Node (Port 5001 for Tradehub API and 1318 for Cosmos)

**Comment by SwitcheoCommunityFund** [comment]
done
