### ISSUE TITLE
Tradehub API Libary is imported, but fully used

### ISSUE THREAD

**Issue by Devel484** [SwitcheoCommunityFund/ethereum-switcheo-tradehub-airdrop#3]
Imported Tradehub Library
https://github.com/SwitcheoCommunityFund/ethereum-switcheo-tradehub-airdrop/blob/12a072fd233cbee0713721eeb8d9452f45dbf424/eth_airdrop.js#L4

Redefined API Request
https://github.com/SwitcheoCommunityFund/ethereum-switcheo-tradehub-airdrop/blob/12a072fd233cbee0713721eeb8d9452f45dbf424/eth_airdrop.js#L65

**Comment by SwitcheoCommunityFund** [comment]
Done
