### ISSUE TITLE
Remove API parameter 'endblock'

### ISSUE THREAD

**Issue by Devel484** [SwitcheoCommunityFund/ethereum-switcheo-tradehub-airdrop#4]
API Parameter 'endblock' is not required and is magic number.

[[Optional Parameters] startblock: starting blockNo to retrieve results, endblock: ending blockNo to retrieve results](https://etherscan.io/apis#accounts)

https://github.com/SwitcheoCommunityFund/ethereum-switcheo-tradehub-airdrop/blob/12a072fd233cbee0713721eeb8d9452f45dbf424/eth_airdrop.js#L220

**Comment by SwitcheoCommunityFund** [comment]
done
