### ISSUE TITLE
New user filter issue

### ISSUE THREAD

**Issue by Aymeric-Born2Stake** [SwitcheoCommunityFund/ethereum-switcheo-tradehub-airdrop#7]
I see that the following address has received the 5 swth airdrop.

https://switcheo.org/account/swth1yxh0lh6grk754wa2sa8852dvtwh8nfpkd8s32m?net=main

But when I look at the history of this wallet, it seems that it did contain swth before, which i guess (as I didn't look deeper) seem to have been transferred to another wallet before an Eth deposit was made. 
So as there were no swth on that wallet at the time of the eth deposit, 5 swth have been airdropped .

I thought the purpose of the airdrop was to give 5 swth to wallets that don't or never had swth before? If a wallet had swth previously, then it shouldn't be considered as a new user.
 
It seems that airdrop is also happening with a wallet containing staked SWTH but zero available SWTH.

So, system should consider 
1) past swth owning history/transactions
2) staked swth

**Comment by SwitcheoCommunityFund** [comment]
It was only once on launch, we decided to airdrop to those folks ourselves =).

**Comment by Aymeric-Born2Stake** [comment]
That doesn't answer my questions. I don't see why you are closing the issue.
What about the fact that it seems your system doesn't check previous swth ownership, or staking status before proceeding with the airdrop?

**Comment by SwitcheoCommunityFund** [comment]
we have a DB for that and all the checks are in place there, discussed it with Devel already. In any case we may add checks to this code as well but switcheo API lacks enough parameters atm to make it solid.

**Comment by SwitcheoCommunityFund** [comment]
And sure, if you just copy paste this code without adding extra checks you will airdrop to those folks as well.

**Comment by SwitcheoCommunityFund** [comment]
And btw just to make it clear for everyone, if a user was using tradehub wallet but didn't create ETH wallet, the moment he creates it the system will check if he has available SWTH and WILL airdrop if he doesn't have and that is exactly how it was intended to work from the very beginning. So if folks for example created accounts long ago and staked all their SWTH and now decided to trade, sent in ETH or ERC-20 tokens to their wallets, created an ETH wallet on top and have no available SWTH at that time they will get an airdrop, yes!
